AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  demo-app 

  Sample demo app to check out the lambda layer

Globals:
  Function:
    Timeout: 30
    Runtime: python3.8
    Architectures:
      - x86_64
    Layers: 
      - arn:aws:lambda:us-east-2:618758721119:layer:PythonLayer:1

Resources:
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: appF/
      Handler: app.lambda_handler   
      Events:
        CreateOperation:
          Type: Api
          Properties:
            Path:  /activities
            Method: post

Outputs:
  CreateFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Create function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/activities/"